[phases.install]
cmds = ["npm install -g corepack@0.24.1 && corepack enable && pnpm install --no-frozen-lockfile --prod=false"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "cd apps/backend && npx prisma db push --accept-data-loss && node dist/main.js"
